// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advance_requests.sql

package db

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdvanceRequestsByUserToday = `-- name: CountAdvanceRequestsByUserToday :one
SELECT COUNT(*) FROM advance_requests
WHERE user_id = $1 AND created_at::date = CURRENT_DATE
`

func (q *Queries) CountAdvanceRequestsByUserToday(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAdvanceRequestsByUserToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuccessfulAdvanceRequestsByUserThisMonth = `-- name: CountSuccessfulAdvanceRequestsByUserThisMonth :one
SELECT COUNT(*) FROM advance_requests
WHERE user_id = $1 AND status = 'success'
    AND date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
`

func (q *Queries) CountSuccessfulAdvanceRequestsByUserThisMonth(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulAdvanceRequestsByUserThisMonth, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdvanceRequest = `-- name: CreateAdvanceRequest :one
INSERT INTO advance_requests (company_id, user_id, amount_xaf, status)
VALUES ($1, $2, $3, $4) RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at
`

type CreateAdvanceRequestParams struct {
	CompanyID uuid.UUID      `json:"company_id"`
	UserID    uuid.UUID      `json:"user_id"`
	AmountXaf pgtype.Numeric `json:"amount_xaf"`
	Status    RequestStatus  `json:"status"`
}

func (q *Queries) CreateAdvanceRequest(ctx context.Context, arg CreateAdvanceRequestParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, createAdvanceRequest,
		arg.CompanyID,
		arg.UserID,
		arg.AmountXaf,
		arg.Status,
	)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRequestByUserID = `-- name: GetActiveRequestByUserID :one
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM advance_requests
WHERE user_id = $1 AND status IN ('initiated', 'processing', 'pending')
LIMIT 1
`

func (q *Queries) GetActiveRequestByUserID(ctx context.Context, userID uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getActiveRequestByUserID, userID)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvanceRequestByCampayRef = `-- name: GetAdvanceRequestByCampayRef :one
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM advance_requests WHERE campay_payout_ref = $1
`

// Webhook resolves by Campay reference (globally unique); no company context.
func (q *Queries) GetAdvanceRequestByCampayRef(ctx context.Context, campayPayoutRef pgtype.Text) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getAdvanceRequestByCampayRef, campayPayoutRef)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvanceRequestByID = `-- name: GetAdvanceRequestByID :one
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM advance_requests WHERE id = $1
`

func (q *Queries) GetAdvanceRequestByID(ctx context.Context, id uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getAdvanceRequestByID, id)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdvanceRequestsByUserID = `-- name: ListAdvanceRequestsByUserID :many
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM advance_requests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdvanceRequestsByUserID(ctx context.Context, userID uuid.UUID) ([]AdvanceRequest, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequestsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceRequest
	for rows.Next() {
		var i AdvanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvanceRequestsWithUserByCompany = `-- name: ListAdvanceRequestsWithUserByCompany :many
SELECT ar.id, ar.company_id, ar.user_id, ar.amount_xaf, ar.status, ar.campay_payout_ref, ar.failure_reason, ar.payout_duration_seconds, ar.attempt_count, ar.last_reconciled_at, ar.next_retry_at, ar.needs_admin_review, ar.created_at, ar.updated_at, u.email AS user_email
FROM advance_requests ar
JOIN users u ON ar.user_id = u.id
WHERE ar.company_id = $1
ORDER BY ar.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAdvanceRequestsWithUserByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListAdvanceRequestsWithUserByCompanyRow struct {
	ID                    uuid.UUID      `json:"id"`
	CompanyID             uuid.UUID      `json:"company_id"`
	UserID                uuid.UUID      `json:"user_id"`
	AmountXaf             pgtype.Numeric `json:"amount_xaf"`
	Status                RequestStatus  `json:"status"`
	CampayPayoutRef       pgtype.Text    `json:"campay_payout_ref"`
	FailureReason         pgtype.Text    `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4    `json:"payout_duration_seconds"`
	AttemptCount          int32          `json:"attempt_count"`
	LastReconciledAt      sql.NullTime   `json:"last_reconciled_at"`
	NextRetryAt           sql.NullTime   `json:"next_retry_at"`
	NeedsAdminReview      bool           `json:"needs_admin_review"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
	UserEmail             string         `json:"user_email"`
}

func (q *Queries) ListAdvanceRequestsWithUserByCompany(ctx context.Context, arg ListAdvanceRequestsWithUserByCompanyParams) ([]ListAdvanceRequestsWithUserByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequestsWithUserByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdvanceRequestsWithUserByCompanyRow
	for rows.Next() {
		var i ListAdvanceRequestsWithUserByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAdvanceRequestStatus = `-- name: UpdateAdvanceRequestStatus :one
UPDATE advance_requests SET
    status = $2,
    failure_reason = $3,
    payout_duration_seconds = $4,
    campay_payout_ref = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at
`

type UpdateAdvanceRequestStatusParams struct {
	ID                    uuid.UUID     `json:"id"`
	Status                RequestStatus `json:"status"`
	FailureReason         pgtype.Text   `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4   `json:"payout_duration_seconds"`
	CampayPayoutRef       pgtype.Text   `json:"campay_payout_ref"`
}

func (q *Queries) UpdateAdvanceRequestStatus(ctx context.Context, arg UpdateAdvanceRequestStatusParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAdvanceRequestStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.PayoutDurationSeconds,
		arg.CampayPayoutRef,
	)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
