// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: advance_requests.sql

package db

import (
	"context"
	"time"

	"github.com/Iknite-Space/bohikor2/internal/dbtypes"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAdvanceRequestsByUserToday = `-- name: CountAdvanceRequestsByUserToday :one
SELECT COUNT(*) FROM advance_requests
WHERE user_id = $1 AND created_at::date = CURRENT_DATE
`

func (q *Queries) CountAdvanceRequestsByUserToday(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAdvanceRequestsByUserToday, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSuccessfulAdvanceRequestsByUserThisMonth = `-- name: CountSuccessfulAdvanceRequestsByUserThisMonth :one
SELECT COUNT(*) FROM advance_requests
WHERE user_id = $1 AND status = 'success'
    AND date_trunc('month', created_at) = date_trunc('month', CURRENT_DATE)
`

func (q *Queries) CountSuccessfulAdvanceRequestsByUserThisMonth(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countSuccessfulAdvanceRequestsByUserThisMonth, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAdvanceRequest = `-- name: CreateAdvanceRequest :one
INSERT INTO advance_requests (company_id, user_id, amount_xaf, status)
VALUES ($1, $2, $3, $4) RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at
`

type CreateAdvanceRequestParams struct {
	CompanyID uuid.UUID             `json:"company_id"`
	UserID    uuid.UUID             `json:"user_id"`
	AmountXaf dbtypes.NumericString `json:"amount_xaf"`
	Status    RequestStatus         `json:"status"`
}

func (q *Queries) CreateAdvanceRequest(ctx context.Context, arg CreateAdvanceRequestParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, createAdvanceRequest,
		arg.CompanyID,
		arg.UserID,
		arg.AmountXaf,
		arg.Status,
	)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAdvanceRequestReissue = `-- name: CreateAdvanceRequestReissue :one
INSERT INTO advance_requests (company_id, user_id, amount_xaf, status, reissued_from_id)
VALUES ($1, $2, $3, $4, $5) RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at
`

type CreateAdvanceRequestReissueParams struct {
	CompanyID      uuid.UUID             `json:"company_id"`
	UserID         uuid.UUID             `json:"user_id"`
	AmountXaf      dbtypes.NumericString `json:"amount_xaf"`
	Status         RequestStatus         `json:"status"`
	ReissuedFromID pgtype.UUID           `json:"reissued_from_id"`
}

func (q *Queries) CreateAdvanceRequestReissue(ctx context.Context, arg CreateAdvanceRequestReissueParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, createAdvanceRequestReissue,
		arg.CompanyID,
		arg.UserID,
		arg.AmountXaf,
		arg.Status,
		arg.ReissuedFromID,
	)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveRequestByUserID = `-- name: GetActiveRequestByUserID :one
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at FROM advance_requests
WHERE user_id = $1 AND status IN ('initiated', 'processing', 'pending')
LIMIT 1
`

func (q *Queries) GetActiveRequestByUserID(ctx context.Context, userID uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getActiveRequestByUserID, userID)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvanceRequestByCampayRef = `-- name: GetAdvanceRequestByCampayRef :one
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at FROM advance_requests WHERE campay_payout_ref = $1
`

// Webhook resolves by Campay reference (globally unique); no company context.
func (q *Queries) GetAdvanceRequestByCampayRef(ctx context.Context, campayPayoutRef pgtype.Text) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getAdvanceRequestByCampayRef, campayPayoutRef)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAdvanceRequestByID = `-- name: GetAdvanceRequestByID :one
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at FROM advance_requests WHERE id = $1
`

func (q *Queries) GetAdvanceRequestByID(ctx context.Context, id uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, getAdvanceRequestByID, id)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAdvanceRequestsByUserID = `-- name: ListAdvanceRequestsByUserID :many
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at FROM advance_requests
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAdvanceRequestsByUserID(ctx context.Context, userID uuid.UUID) ([]AdvanceRequest, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequestsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceRequest
	for rows.Next() {
		var i AdvanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.ReissuedFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdvanceRequestsWithUserByCompany = `-- name: ListAdvanceRequestsWithUserByCompany :many
SELECT ar.id, ar.company_id, ar.user_id, ar.amount_xaf, ar.status, ar.campay_payout_ref, ar.failure_reason, ar.payout_duration_seconds, ar.attempt_count, ar.last_reconciled_at, ar.next_retry_at, ar.needs_admin_review, ar.reissued_from_id, ar.created_at, ar.updated_at, u.email AS user_email
FROM advance_requests ar
JOIN users u ON ar.user_id = u.id
WHERE ar.company_id = $1
ORDER BY ar.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAdvanceRequestsWithUserByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

type ListAdvanceRequestsWithUserByCompanyRow struct {
	ID                    uuid.UUID             `json:"id"`
	CompanyID             uuid.UUID             `json:"company_id"`
	UserID                uuid.UUID             `json:"user_id"`
	AmountXaf             dbtypes.NumericString `json:"amount_xaf"`
	Status                RequestStatus         `json:"status"`
	CampayPayoutRef       pgtype.Text           `json:"campay_payout_ref"`
	FailureReason         pgtype.Text           `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4           `json:"payout_duration_seconds"`
	AttemptCount          int32                 `json:"attempt_count"`
	LastReconciledAt      pgtype.Timestamptz    `json:"last_reconciled_at"`
	NextRetryAt           pgtype.Timestamptz    `json:"next_retry_at"`
	NeedsAdminReview      bool                  `json:"needs_admin_review"`
	ReissuedFromID        pgtype.UUID           `json:"reissued_from_id"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
	UserEmail             string                `json:"user_email"`
}

func (q *Queries) ListAdvanceRequestsWithUserByCompany(ctx context.Context, arg ListAdvanceRequestsWithUserByCompanyParams) ([]ListAdvanceRequestsWithUserByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listAdvanceRequestsWithUserByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdvanceRequestsWithUserByCompanyRow
	for rows.Next() {
		var i ListAdvanceRequestsWithUserByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.ReissuedFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompanyRequestHealth = `-- name: ListCompanyRequestHealth :many
SELECT
    c.id AS company_id,
    c.slug AS company_slug,
    c.name AS company_name,
    COUNT(*) FILTER (WHERE ar.status = 'processing') AS processing_count,
    COUNT(*) FILTER (WHERE ar.status = 'pending') AS pending_count,
    COUNT(*) FILTER (WHERE ar.needs_admin_review) AS needs_review_count
FROM companies c
LEFT JOIN advance_requests ar
    ON ar.company_id = c.id
    AND (ar.status IN ('processing', 'pending') OR ar.needs_admin_review)
GROUP BY c.id, c.slug, c.name
ORDER BY needs_review_count DESC, processing_count DESC, pending_count DESC
`

type ListCompanyRequestHealthRow struct {
	CompanyID        uuid.UUID `json:"company_id"`
	CompanySlug      string    `json:"company_slug"`
	CompanyName      string    `json:"company_name"`
	ProcessingCount  int64     `json:"processing_count"`
	PendingCount     int64     `json:"pending_count"`
	NeedsReviewCount int64     `json:"needs_review_count"`
}

// Per-company counts of in-flight/stuck payout states, for the platform
// console's reconciliation health overview. The join is bounded to
// non-terminal/flagged rows so cost scales with the in-flight queue size,
// not each company's full lifetime request history.
func (q *Queries) ListCompanyRequestHealth(ctx context.Context) ([]ListCompanyRequestHealthRow, error) {
	rows, err := q.db.Query(ctx, listCompanyRequestHealth)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompanyRequestHealthRow
	for rows.Next() {
		var i ListCompanyRequestHealthRow
		if err := rows.Scan(
			&i.CompanyID,
			&i.CompanySlug,
			&i.CompanyName,
			&i.ProcessingCount,
			&i.PendingCount,
			&i.NeedsReviewCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcilableAdvanceRequests = `-- name: ListReconcilableAdvanceRequests :many
SELECT id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at FROM advance_requests
WHERE needs_admin_review = FALSE
  AND (
    (status IN ('processing', 'pending') AND campay_payout_ref IS NOT NULL AND (next_retry_at IS NULL OR next_retry_at <= NOW()))
    OR (status = 'processing' AND campay_payout_ref IS NULL)
    OR (status = 'initiated' AND created_at <= NOW() - INTERVAL '60 seconds')
  )
ORDER BY created_at ASC
`

// Rows the reconciler must act on: ref'd processing/pending rows past their
// next_retry_at (a NULL next_retry_at means "never yet scheduled" — treated
// as due immediately so a row transitioned to processing/pending without
// explicitly setting next_retry_at, e.g. the post-transfer-DB-update-failure
// fallback in CreateRequest, is still picked up on the very next tick);
// processing rows with no campay_payout_ref (pure timeout/crash, nothing to
// poll — surfaced every tick, self-gated by the reconciler's own grace-period
// check since polling isn't possible for this class); or initiated rows old
// enough to be a process-crash artifact (debit committed, server died before
// the Campay call returned). Excludes rows already flagged for a human.
func (q *Queries) ListReconcilableAdvanceRequests(ctx context.Context) ([]AdvanceRequest, error) {
	rows, err := q.db.Query(ctx, listReconcilableAdvanceRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AdvanceRequest
	for rows.Next() {
		var i AdvanceRequest
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.ReissuedFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequestsNeedingReviewAcrossCompanies = `-- name: ListRequestsNeedingReviewAcrossCompanies :many
SELECT ar.id, ar.company_id, ar.user_id, ar.amount_xaf, ar.status, ar.campay_payout_ref, ar.failure_reason, ar.payout_duration_seconds, ar.attempt_count, ar.last_reconciled_at, ar.next_retry_at, ar.needs_admin_review, ar.reissued_from_id, ar.created_at, ar.updated_at, c.slug AS company_slug, c.name AS company_name, u.email AS user_email
FROM advance_requests ar
JOIN companies c ON c.id = ar.company_id
JOIN users u ON u.id = ar.user_id
WHERE ar.needs_admin_review = TRUE
ORDER BY ar.updated_at DESC
LIMIT 500
`

type ListRequestsNeedingReviewAcrossCompaniesRow struct {
	ID                    uuid.UUID             `json:"id"`
	CompanyID             uuid.UUID             `json:"company_id"`
	UserID                uuid.UUID             `json:"user_id"`
	AmountXaf             dbtypes.NumericString `json:"amount_xaf"`
	Status                RequestStatus         `json:"status"`
	CampayPayoutRef       pgtype.Text           `json:"campay_payout_ref"`
	FailureReason         pgtype.Text           `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4           `json:"payout_duration_seconds"`
	AttemptCount          int32                 `json:"attempt_count"`
	LastReconciledAt      pgtype.Timestamptz    `json:"last_reconciled_at"`
	NextRetryAt           pgtype.Timestamptz    `json:"next_retry_at"`
	NeedsAdminReview      bool                  `json:"needs_admin_review"`
	ReissuedFromID        pgtype.UUID           `json:"reissued_from_id"`
	CreatedAt             time.Time             `json:"created_at"`
	UpdatedAt             time.Time             `json:"updated_at"`
	CompanySlug           string                `json:"company_slug"`
	CompanyName           string                `json:"company_name"`
	UserEmail             string                `json:"user_email"`
}

// Platform-admin visibility into the needs_admin_review queue across every
// company (the reconciler's escalation path today only surfaces per-company,
// via /api/admin/requests, so there was no cross-tenant view of stuck
// payouts before this query). Backed by the partial index
// idx_advance_requests_needs_admin_review. This queue is expected to stay
// near-empty in healthy operation (it only grows when the reconciler in
// internal/reconciler/ has given up on a row after its full backoff ladder);
// the LIMIT is a safety cap against unbounded growth during a sustained
// Campay outage, not pagination for routine browsing.
func (q *Queries) ListRequestsNeedingReviewAcrossCompanies(ctx context.Context) ([]ListRequestsNeedingReviewAcrossCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listRequestsNeedingReviewAcrossCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRequestsNeedingReviewAcrossCompaniesRow
	for rows.Next() {
		var i ListRequestsNeedingReviewAcrossCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AmountXaf,
			&i.Status,
			&i.CampayPayoutRef,
			&i.FailureReason,
			&i.PayoutDurationSeconds,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.ReissuedFromID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanySlug,
			&i.CompanyName,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveAdvanceRequest = `-- name: ResolveAdvanceRequest :one
UPDATE advance_requests SET needs_admin_review = FALSE, updated_at = NOW()
WHERE id = $1 AND needs_admin_review = TRUE RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at
`

func (q *Queries) ResolveAdvanceRequest(ctx context.Context, id uuid.UUID) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, resolveAdvanceRequest, id)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdvanceRequestReconcileAttempt = `-- name: UpdateAdvanceRequestReconcileAttempt :one
UPDATE advance_requests SET
    attempt_count = attempt_count + 1,
    last_reconciled_at = NOW(),
    next_retry_at = $2,
    needs_admin_review = $3,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at
`

type UpdateAdvanceRequestReconcileAttemptParams struct {
	ID               uuid.UUID          `json:"id"`
	NextRetryAt      pgtype.Timestamptz `json:"next_retry_at"`
	NeedsAdminReview bool               `json:"needs_admin_review"`
}

func (q *Queries) UpdateAdvanceRequestReconcileAttempt(ctx context.Context, arg UpdateAdvanceRequestReconcileAttemptParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAdvanceRequestReconcileAttempt, arg.ID, arg.NextRetryAt, arg.NeedsAdminReview)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAdvanceRequestStatus = `-- name: UpdateAdvanceRequestStatus :one
UPDATE advance_requests SET
    status = $2,
    failure_reason = $3,
    payout_duration_seconds = $4,
    campay_payout_ref = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, user_id, amount_xaf, status, campay_payout_ref, failure_reason, payout_duration_seconds, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, reissued_from_id, created_at, updated_at
`

type UpdateAdvanceRequestStatusParams struct {
	ID                    uuid.UUID     `json:"id"`
	Status                RequestStatus `json:"status"`
	FailureReason         pgtype.Text   `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4   `json:"payout_duration_seconds"`
	CampayPayoutRef       pgtype.Text   `json:"campay_payout_ref"`
}

func (q *Queries) UpdateAdvanceRequestStatus(ctx context.Context, arg UpdateAdvanceRequestStatusParams) (AdvanceRequest, error) {
	row := q.db.QueryRow(ctx, updateAdvanceRequestStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.PayoutDurationSeconds,
		arg.CampayPayoutRef,
	)
	var i AdvanceRequest
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AmountXaf,
		&i.Status,
		&i.CampayPayoutRef,
		&i.FailureReason,
		&i.PayoutDurationSeconds,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.ReissuedFromID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
