// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: company_ledger.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO company_ledger (company_id, entry_type, amount_xaf, advance_request_id, created_by, note)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, company_id, entry_type, amount_xaf, advance_request_id, created_by, note, created_at
`

type CreateLedgerEntryParams struct {
	CompanyID        uuid.UUID      `json:"company_id"`
	EntryType        string         `json:"entry_type"`
	AmountXaf        pgtype.Numeric `json:"amount_xaf"`
	AdvanceRequestID pgtype.UUID    `json:"advance_request_id"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
	Note             pgtype.Text    `json:"note"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (CompanyLedger, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.CompanyID,
		arg.EntryType,
		arg.AmountXaf,
		arg.AdvanceRequestID,
		arg.CreatedBy,
		arg.Note,
	)
	var i CompanyLedger
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.EntryType,
		&i.AmountXaf,
		&i.AdvanceRequestID,
		&i.CreatedBy,
		&i.Note,
		&i.CreatedAt,
	)
	return i, err
}

const getCompanyBalance = `-- name: GetCompanyBalance :one
SELECT COALESCE(SUM(amount_xaf), 0)::NUMERIC(14, 2) AS balance
FROM company_ledger WHERE company_id = $1
`

func (q *Queries) GetCompanyBalance(ctx context.Context, companyID uuid.UUID) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getCompanyBalance, companyID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const listLedgerByCompany = `-- name: ListLedgerByCompany :many
SELECT id, company_id, entry_type, amount_xaf, advance_request_id, created_by, note, created_at FROM company_ledger
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLedgerByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListLedgerByCompany(ctx context.Context, arg ListLedgerByCompanyParams) ([]CompanyLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CompanyLedger
	for rows.Next() {
		var i CompanyLedger
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.EntryType,
			&i.AmountXaf,
			&i.AdvanceRequestID,
			&i.CreatedBy,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
