// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createCompany = `-- name: CreateCompany :one
INSERT INTO companies (slug, name, created_by)
VALUES ($1, $2, $3) RETURNING id, slug, name, status, created_by, created_at, updated_at
`

type CreateCompanyParams struct {
	Slug      string      `json:"slug"`
	Name      string      `json:"name"`
	CreatedBy pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (Company, error) {
	row := q.db.QueryRow(ctx, createCompany, arg.Slug, arg.Name, arg.CreatedBy)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyByID = `-- name: GetCompanyByID :one
SELECT id, slug, name, status, created_by, created_at, updated_at FROM companies WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCompanyByID(ctx context.Context, id uuid.UUID) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyByID, id)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyBySlug = `-- name: GetCompanyBySlug :one
SELECT id, slug, name, status, created_by, created_at, updated_at FROM companies WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCompanyBySlug(ctx context.Context, slug string) (Company, error) {
	row := q.db.QueryRow(ctx, getCompanyBySlug, slug)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, slug, name, status, created_by, created_at, updated_at FROM companies ORDER BY created_at DESC
`

func (q *Queries) ListCompanies(ctx context.Context) ([]Company, error) {
	rows, err := q.db.Query(ctx, listCompanies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Company
	for rows.Next() {
		var i Company
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesWithBalance = `-- name: ListCompaniesWithBalance :many
SELECT c.id, c.slug, c.name, c.status, c.created_by, c.created_at, c.updated_at, COALESCE(SUM(cl.amount_xaf), 0)::NUMERIC(14, 2) AS balance
FROM companies c
LEFT JOIN company_ledger cl ON cl.company_id = c.id
GROUP BY c.id
ORDER BY c.created_at DESC
`

type ListCompaniesWithBalanceRow struct {
	ID        uuid.UUID      `json:"id"`
	Slug      string         `json:"slug"`
	Name      string         `json:"name"`
	Status    CompanyStatus  `json:"status"`
	CreatedBy pgtype.UUID    `json:"created_by"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	Balance   pgtype.Numeric `json:"balance"`
}

func (q *Queries) ListCompaniesWithBalance(ctx context.Context) ([]ListCompaniesWithBalanceRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesWithBalance)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCompaniesWithBalanceRow
	for rows.Next() {
		var i ListCompaniesWithBalanceRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Status,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCompanyStatus = `-- name: UpdateCompanyStatus :one
UPDATE companies SET status = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, slug, name, status, created_by, created_at, updated_at
`

type UpdateCompanyStatusParams struct {
	ID     uuid.UUID     `json:"id"`
	Status CompanyStatus `json:"status"`
}

func (q *Queries) UpdateCompanyStatus(ctx context.Context, arg UpdateCompanyStatusParams) (Company, error) {
	row := q.db.QueryRow(ctx, updateCompanyStatus, arg.ID, arg.Status)
	var i Company
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Status,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
