// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: email_otp_failures.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEmailOTPFailure = `-- name: GetEmailOTPFailure :one
SELECT email, consecutive_failures, last_failure_date, blocked_until, is_permanently_blocked, created_at, updated_at FROM email_otp_failures WHERE email = $1
`

func (q *Queries) GetEmailOTPFailure(ctx context.Context, email string) (EmailOtpFailure, error) {
	row := q.db.QueryRow(ctx, getEmailOTPFailure, email)
	var i EmailOtpFailure
	err := row.Scan(
		&i.Email,
		&i.ConsecutiveFailures,
		&i.LastFailureDate,
		&i.BlockedUntil,
		&i.IsPermanentlyBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetEmailOTPFailures = `-- name: ResetEmailOTPFailures :exec
DELETE FROM email_otp_failures WHERE email = $1
`

func (q *Queries) ResetEmailOTPFailures(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, resetEmailOTPFailures, email)
	return err
}

const upsertEmailOTPFailure = `-- name: UpsertEmailOTPFailure :one
INSERT INTO email_otp_failures (email, consecutive_failures, last_failure_date, blocked_until, is_permanently_blocked, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW())
ON CONFLICT (email) DO UPDATE SET
    consecutive_failures = EXCLUDED.consecutive_failures,
    last_failure_date = EXCLUDED.last_failure_date,
    blocked_until = EXCLUDED.blocked_until,
    is_permanently_blocked = EXCLUDED.is_permanently_blocked,
    updated_at = NOW()
RETURNING email, consecutive_failures, last_failure_date, blocked_until, is_permanently_blocked, created_at, updated_at
`

type UpsertEmailOTPFailureParams struct {
	Email                string             `json:"email"`
	ConsecutiveFailures  int32              `json:"consecutive_failures"`
	LastFailureDate      pgtype.Date        `json:"last_failure_date"`
	BlockedUntil         pgtype.Timestamptz `json:"blocked_until"`
	IsPermanentlyBlocked bool               `json:"is_permanently_blocked"`
}

func (q *Queries) UpsertEmailOTPFailure(ctx context.Context, arg UpsertEmailOTPFailureParams) (EmailOtpFailure, error) {
	row := q.db.QueryRow(ctx, upsertEmailOTPFailure,
		arg.Email,
		arg.ConsecutiveFailures,
		arg.LastFailureDate,
		arg.BlockedUntil,
		arg.IsPermanentlyBlocked,
	)
	var i EmailOtpFailure
	err := row.Scan(
		&i.Email,
		&i.ConsecutiveFailures,
		&i.LastFailureDate,
		&i.BlockedUntil,
		&i.IsPermanentlyBlocked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
