// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: events.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (company_id, user_id, admin_id, event_type, metadata)
VALUES ($1, $2, $3, $4, $5) RETURNING id, company_id, user_id, admin_id, event_type, metadata, created_at
`

type CreateEventParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	UserID    pgtype.UUID `json:"user_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRow(ctx, createEvent,
		arg.CompanyID,
		arg.UserID,
		arg.AdminID,
		arg.EventType,
		arg.Metadata,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.AdminID,
		&i.EventType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsWithUserByCompany = `-- name: ListEventsWithUserByCompany :many
SELECT e.id, e.company_id, e.user_id, e.admin_id, e.event_type, e.metadata, e.created_at, u.email AS user_email
FROM events e
LEFT JOIN users u ON e.user_id = u.id
WHERE e.company_id = $1
ORDER BY e.created_at DESC
LIMIT $2 OFFSET $3
`

type ListEventsWithUserByCompanyParams struct {
	CompanyID pgtype.UUID `json:"company_id"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

type ListEventsWithUserByCompanyRow struct {
	ID        uuid.UUID   `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
	UserID    pgtype.UUID `json:"user_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
	UserEmail pgtype.Text `json:"user_email"`
}

func (q *Queries) ListEventsWithUserByCompany(ctx context.Context, arg ListEventsWithUserByCompanyParams) ([]ListEventsWithUserByCompanyRow, error) {
	rows, err := q.db.Query(ctx, listEventsWithUserByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEventsWithUserByCompanyRow
	for rows.Next() {
		var i ListEventsWithUserByCompanyRow
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.AdminID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
			&i.UserEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
