// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invitations_list.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listInvitationsByCompany = `-- name: ListInvitationsByCompany :many
SELECT id, company_id, email, status, invited_by, sent_at, accepted_at, updated_at FROM invitations WHERE company_id = $1 ORDER BY sent_at DESC
`

func (q *Queries) ListInvitationsByCompany(ctx context.Context, companyID uuid.UUID) ([]Invitation, error) {
	rows, err := q.db.Query(ctx, listInvitationsByCompany, companyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Invitation
	for rows.Next() {
		var i Invitation
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.Status,
			&i.InvitedBy,
			&i.SentAt,
			&i.AcceptedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
