// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CompanyStatus string

const (
	CompanyStatusActive    CompanyStatus = "active"
	CompanyStatusSuspended CompanyStatus = "suspended"
)

func (e *CompanyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CompanyStatus(s)
	case string:
		*e = CompanyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CompanyStatus: %T", src)
	}
	return nil
}

type NullCompanyStatus struct {
	CompanyStatus CompanyStatus `json:"company_status"`
	Valid         bool          `json:"valid"` // Valid is true if CompanyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCompanyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CompanyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CompanyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCompanyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CompanyStatus), nil
}

type InvitationStatus string

const (
	InvitationStatusPending  InvitationStatus = "pending"
	InvitationStatusSent     InvitationStatus = "sent"
	InvitationStatusAccepted InvitationStatus = "accepted"
	InvitationStatusRevoked  InvitationStatus = "revoked"
	InvitationStatusFailed   InvitationStatus = "failed"
)

func (e *InvitationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvitationStatus(s)
	case string:
		*e = InvitationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvitationStatus: %T", src)
	}
	return nil
}

type NullInvitationStatus struct {
	InvitationStatus InvitationStatus `json:"invitation_status"`
	Valid            bool             `json:"valid"` // Valid is true if InvitationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvitationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvitationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvitationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvitationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvitationStatus), nil
}

type RequestStatus string

const (
	RequestStatusInitiated  RequestStatus = "initiated"
	RequestStatusProcessing RequestStatus = "processing"
	RequestStatusPending    RequestStatus = "pending"
	RequestStatusSuccess    RequestStatus = "success"
	RequestStatusFailed     RequestStatus = "failed"
)

func (e *RequestStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RequestStatus(s)
	case string:
		*e = RequestStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for RequestStatus: %T", src)
	}
	return nil
}

type NullRequestStatus struct {
	RequestStatus RequestStatus `json:"request_status"`
	Valid         bool          `json:"valid"` // Valid is true if RequestStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRequestStatus) Scan(value interface{}) error {
	if value == nil {
		ns.RequestStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RequestStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRequestStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RequestStatus), nil
}

type UserStatus string

const (
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
	UserStatusLocked    UserStatus = "locked"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus `json:"user_status"`
	Valid      bool       `json:"valid"` // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type Admin struct {
	ID           uuid.UUID `json:"id"`
	CompanyID    uuid.UUID `json:"company_id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type AdvanceRequest struct {
	ID                    uuid.UUID      `json:"id"`
	CompanyID             uuid.UUID      `json:"company_id"`
	UserID                uuid.UUID      `json:"user_id"`
	AmountXaf             pgtype.Numeric `json:"amount_xaf"`
	Status                RequestStatus  `json:"status"`
	CampayPayoutRef       pgtype.Text    `json:"campay_payout_ref"`
	FailureReason         pgtype.Text    `json:"failure_reason"`
	PayoutDurationSeconds pgtype.Int4    `json:"payout_duration_seconds"`
	AttemptCount          int32          `json:"attempt_count"`
	LastReconciledAt      sql.NullTime   `json:"last_reconciled_at"`
	NextRetryAt           sql.NullTime   `json:"next_retry_at"`
	NeedsAdminReview      bool           `json:"needs_admin_review"`
	CreatedAt             time.Time      `json:"created_at"`
	UpdatedAt             time.Time      `json:"updated_at"`
}

type Company struct {
	ID        uuid.UUID     `json:"id"`
	Slug      string        `json:"slug"`
	Name      string        `json:"name"`
	Status    CompanyStatus `json:"status"`
	CreatedBy pgtype.UUID   `json:"created_by"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
}

type CompanyLedger struct {
	ID               uuid.UUID      `json:"id"`
	CompanyID        uuid.UUID      `json:"company_id"`
	EntryType        string         `json:"entry_type"`
	AmountXaf        pgtype.Numeric `json:"amount_xaf"`
	AdvanceRequestID pgtype.UUID    `json:"advance_request_id"`
	CreatedBy        pgtype.UUID    `json:"created_by"`
	Note             pgtype.Text    `json:"note"`
	CreatedAt        time.Time      `json:"created_at"`
}

type EmailOtp struct {
	ID        uuid.UUID `json:"id"`
	Email     string    `json:"email"`
	Code      string    `json:"code"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type EmailOtpFailure struct {
	Email                string       `json:"email"`
	ConsecutiveFailures  int32        `json:"consecutive_failures"`
	LastFailureDate      pgtype.Date  `json:"last_failure_date"`
	BlockedUntil         sql.NullTime `json:"blocked_until"`
	IsPermanentlyBlocked bool         `json:"is_permanently_blocked"`
	CreatedAt            time.Time    `json:"created_at"`
	UpdatedAt            time.Time    `json:"updated_at"`
}

type Event struct {
	ID        uuid.UUID   `json:"id"`
	CompanyID pgtype.UUID `json:"company_id"`
	UserID    pgtype.UUID `json:"user_id"`
	AdminID   pgtype.UUID `json:"admin_id"`
	EventType string      `json:"event_type"`
	Metadata  []byte      `json:"metadata"`
	CreatedAt time.Time   `json:"created_at"`
}

type Invitation struct {
	ID         uuid.UUID        `json:"id"`
	CompanyID  uuid.UUID        `json:"company_id"`
	Email      string           `json:"email"`
	Status     InvitationStatus `json:"status"`
	InvitedBy  pgtype.UUID      `json:"invited_by"`
	SentAt     time.Time        `json:"sent_at"`
	AcceptedAt sql.NullTime     `json:"accepted_at"`
	UpdatedAt  time.Time        `json:"updated_at"`
}

type PhoneVerification struct {
	ID              uuid.UUID      `json:"id"`
	CompanyID       uuid.UUID      `json:"company_id"`
	UserID          uuid.UUID      `json:"user_id"`
	PhoneNumber     string         `json:"phone_number"`
	AmountXaf       pgtype.Numeric `json:"amount_xaf"`
	CampayPayoutRef pgtype.Text    `json:"campay_payout_ref"`
	Status          RequestStatus  `json:"status"`
	FailureReason   pgtype.Text    `json:"failure_reason"`
	UssdCode        pgtype.Text    `json:"ussd_code"`
	CreatedAt       time.Time      `json:"created_at"`
	UpdatedAt       time.Time      `json:"updated_at"`
}

type PlatformAdmin struct {
	ID           uuid.UUID `json:"id"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
	CreatedAt    time.Time `json:"created_at"`
}

type RefreshToken struct {
	ID          uuid.UUID `json:"id"`
	TokenHash   string    `json:"token_hash"`
	SubjectID   uuid.UUID `json:"subject_id"`
	SubjectType string    `json:"subject_type"`
	ExpiresAt   time.Time `json:"expires_at"`
	CreatedAt   time.Time `json:"created_at"`
}

type Setting struct {
	CompanyID uuid.UUID   `json:"company_id"`
	Key       string      `json:"key"`
	Value     []byte      `json:"value"`
	UpdatedAt time.Time   `json:"updated_at"`
	UpdatedBy pgtype.UUID `json:"updated_by"`
}

type User struct {
	ID                  uuid.UUID    `json:"id"`
	CompanyID           uuid.UUID    `json:"company_id"`
	Email               string       `json:"email"`
	EmailVerified       bool         `json:"email_verified"`
	FullName            pgtype.Text  `json:"full_name"`
	PhoneNumber         pgtype.Text  `json:"phone_number"`
	PhoneVerified       bool         `json:"phone_verified"`
	PinHash             pgtype.Text  `json:"pin_hash"`
	FailedLoginAttempts int32        `json:"failed_login_attempts"`
	LockedUntil         sql.NullTime `json:"locked_until"`
	Status              UserStatus   `json:"status"`
	IsTermsAccepted     bool         `json:"is_terms_accepted"`
	TermsAcceptedAt     sql.NullTime `json:"terms_accepted_at"`
	TermsVersion        pgtype.Text  `json:"terms_version"`
	UserIpAtConsent     *netip.Addr  `json:"user_ip_at_consent"`
	CreatedAt           time.Time    `json:"created_at"`
	UpdatedAt           time.Time    `json:"updated_at"`
}
