// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_verifications.sql

package db

import (
	"context"

	"github.com/Iknite-Space/bohikor2/internal/dbtypes"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoneVerification = `-- name: CreatePhoneVerification :one
INSERT INTO phone_verifications (company_id, user_id, phone_number, amount_xaf, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, created_at, updated_at
`

type CreatePhoneVerificationParams struct {
	CompanyID   uuid.UUID             `json:"company_id"`
	UserID      uuid.UUID             `json:"user_id"`
	PhoneNumber string                `json:"phone_number"`
	AmountXaf   dbtypes.NumericString `json:"amount_xaf"`
	Status      RequestStatus         `json:"status"`
}

func (q *Queries) CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, createPhoneVerification,
		arg.CompanyID,
		arg.UserID,
		arg.PhoneNumber,
		arg.AmountXaf,
		arg.Status,
	)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePhoneVerificationByUser = `-- name: GetActivePhoneVerificationByUser :one
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, created_at, updated_at FROM phone_verifications
WHERE user_id = $1 AND status IN ('initiated', 'processing', 'pending')
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetActivePhoneVerificationByUser(ctx context.Context, userID uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getActivePhoneVerificationByUser, userID)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPhoneVerificationByUser = `-- name: GetLatestPhoneVerificationByUser :one
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, created_at, updated_at FROM phone_verifications
WHERE user_id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestPhoneVerificationByUser(ctx context.Context, userID uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getLatestPhoneVerificationByUser, userID)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneVerificationByCampayRef = `-- name: GetPhoneVerificationByCampayRef :one
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, created_at, updated_at FROM phone_verifications WHERE campay_payout_ref = $1
`

// Webhook resolves by Campay reference (globally unique); no company context.
func (q *Queries) GetPhoneVerificationByCampayRef(ctx context.Context, campayPayoutRef pgtype.Text) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getPhoneVerificationByCampayRef, campayPayoutRef)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoneVerificationStatus = `-- name: UpdatePhoneVerificationStatus :one
UPDATE phone_verifications SET
    status = $2,
    failure_reason = $3,
    campay_payout_ref = $4,
    ussd_code = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, created_at, updated_at
`

type UpdatePhoneVerificationStatusParams struct {
	ID              uuid.UUID     `json:"id"`
	Status          RequestStatus `json:"status"`
	FailureReason   pgtype.Text   `json:"failure_reason"`
	CampayPayoutRef pgtype.Text   `json:"campay_payout_ref"`
	UssdCode        pgtype.Text   `json:"ussd_code"`
}

func (q *Queries) UpdatePhoneVerificationStatus(ctx context.Context, arg UpdatePhoneVerificationStatusParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, updatePhoneVerificationStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.CampayPayoutRef,
		arg.UssdCode,
	)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
