// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_otps.sql

package db

import (
	"context"
	"time"
)

const cleanupExpiredPhoneOTPs = `-- name: CleanupExpiredPhoneOTPs :exec
DELETE FROM phone_otps WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredPhoneOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredPhoneOTPs)
	return err
}

const createPhoneOTP = `-- name: CreatePhoneOTP :one
INSERT INTO phone_otps (phone_number, code, expires_at)
VALUES ($1, $2, $3) RETURNING id, phone_number, code, expires_at, created_at
`

type CreatePhoneOTPParams struct {
	PhoneNumber string    `json:"phone_number"`
	Code        string    `json:"code"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreatePhoneOTP(ctx context.Context, arg CreatePhoneOTPParams) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, createPhoneOTP, arg.PhoneNumber, arg.Code, arg.ExpiresAt)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const deletePhoneOTP = `-- name: DeletePhoneOTP :exec
DELETE FROM phone_otps WHERE phone_number = $1
`

func (q *Queries) DeletePhoneOTP(ctx context.Context, phoneNumber string) error {
	_, err := q.db.Exec(ctx, deletePhoneOTP, phoneNumber)
	return err
}

const getPhoneOTPByPhoneNumber = `-- name: GetPhoneOTPByPhoneNumber :one
SELECT id, phone_number, code, expires_at, created_at FROM phone_otps WHERE phone_number = $1 AND expires_at > NOW() ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetPhoneOTPByPhoneNumber(ctx context.Context, phoneNumber string) (PhoneOtp, error) {
	row := q.db.QueryRow(ctx, getPhoneOTPByPhoneNumber, phoneNumber)
	var i PhoneOtp
	err := row.Scan(
		&i.ID,
		&i.PhoneNumber,
		&i.Code,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
