// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: phone_verifications.sql

package db

import (
	"context"

	"github.com/Iknite-Space/bohikor2/internal/dbtypes"
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPhoneVerification = `-- name: CreatePhoneVerification :one
INSERT INTO phone_verifications (company_id, user_id, phone_number, amount_xaf, status)
VALUES ($1, $2, $3, $4, $5) RETURNING id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at
`

type CreatePhoneVerificationParams struct {
	CompanyID   uuid.UUID             `json:"company_id"`
	UserID      uuid.UUID             `json:"user_id"`
	PhoneNumber string                `json:"phone_number"`
	AmountXaf   dbtypes.NumericString `json:"amount_xaf"`
	Status      RequestStatus         `json:"status"`
}

func (q *Queries) CreatePhoneVerification(ctx context.Context, arg CreatePhoneVerificationParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, createPhoneVerification,
		arg.CompanyID,
		arg.UserID,
		arg.PhoneNumber,
		arg.AmountXaf,
		arg.Status,
	)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePhoneVerificationByUser = `-- name: GetActivePhoneVerificationByUser :one
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM phone_verifications
WHERE user_id = $1 AND status IN ('initiated', 'processing', 'pending')
  AND created_at > NOW() - INTERVAL '60 seconds'
ORDER BY created_at DESC LIMIT 1
`

// Age-bounded to 60s to match the frontend's own retry affordance
// (bohikor/.../account/page.tsx's canRetry lets the user resubmit once a
// pending/initiated verification is >=60s old) — without this bound, a
// verification stuck on a lost webhook would 409-block every retry attempt
// until the reconciler's full backoff ladder (~23min) gives up on it.
// Older stuck rows are left for the reconciler to keep resolving in the
// background; the user is just no longer blocked from starting a fresh one.
func (q *Queries) GetActivePhoneVerificationByUser(ctx context.Context, userID uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getActivePhoneVerificationByUser, userID)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLatestPhoneVerificationByUser = `-- name: GetLatestPhoneVerificationByUser :one
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM phone_verifications
WHERE user_id = $1
ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetLatestPhoneVerificationByUser(ctx context.Context, userID uuid.UUID) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getLatestPhoneVerificationByUser, userID)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPhoneVerificationByCampayRef = `-- name: GetPhoneVerificationByCampayRef :one
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM phone_verifications WHERE campay_payout_ref = $1
`

// Webhook resolves by Campay reference (globally unique); no company context.
func (q *Queries) GetPhoneVerificationByCampayRef(ctx context.Context, campayPayoutRef pgtype.Text) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, getPhoneVerificationByCampayRef, campayPayoutRef)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listReconcilablePhoneVerifications = `-- name: ListReconcilablePhoneVerifications :many
SELECT id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at FROM phone_verifications
WHERE needs_admin_review = FALSE
  AND (
    (status = 'pending' AND campay_payout_ref IS NOT NULL AND (next_retry_at IS NULL OR next_retry_at <= NOW()))
    OR (status = 'initiated' AND created_at <= NOW() - INTERVAL '60 seconds')
  )
ORDER BY created_at ASC
`

// Mirrors ListReconcilableAdvanceRequests (see that query's comment for the
// full rationale): ref'd pending rows past their next_retry_at, or
// initiated rows old enough to be a process-crash artifact (row created but
// the Campay collect call, or the follow-up status write, never completed).
// Phone verification never uses 'processing' (status only ever moves
// initiated -> pending -> success/failed), so unlike advance_requests there
// is no "processing with no ref" case to cover here. Excludes rows already
// flagged for a human.
func (q *Queries) ListReconcilablePhoneVerifications(ctx context.Context) ([]PhoneVerification, error) {
	rows, err := q.db.Query(ctx, listReconcilablePhoneVerifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PhoneVerification
	for rows.Next() {
		var i PhoneVerification
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.UserID,
			&i.PhoneNumber,
			&i.AmountXaf,
			&i.CampayPayoutRef,
			&i.Status,
			&i.FailureReason,
			&i.UssdCode,
			&i.AttemptCount,
			&i.LastReconciledAt,
			&i.NextRetryAt,
			&i.NeedsAdminReview,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePhoneVerificationReconcileAttempt = `-- name: UpdatePhoneVerificationReconcileAttempt :one
UPDATE phone_verifications SET
    attempt_count = attempt_count + 1,
    last_reconciled_at = NOW(),
    next_retry_at = $2,
    needs_admin_review = $3,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at
`

type UpdatePhoneVerificationReconcileAttemptParams struct {
	ID               uuid.UUID          `json:"id"`
	NextRetryAt      pgtype.Timestamptz `json:"next_retry_at"`
	NeedsAdminReview bool               `json:"needs_admin_review"`
}

func (q *Queries) UpdatePhoneVerificationReconcileAttempt(ctx context.Context, arg UpdatePhoneVerificationReconcileAttemptParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, updatePhoneVerificationReconcileAttempt, arg.ID, arg.NextRetryAt, arg.NeedsAdminReview)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoneVerificationStatus = `-- name: UpdatePhoneVerificationStatus :one
UPDATE phone_verifications SET
    status = $2,
    failure_reason = $3,
    campay_payout_ref = $4,
    ussd_code = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, user_id, phone_number, amount_xaf, campay_payout_ref, status, failure_reason, ussd_code, attempt_count, last_reconciled_at, next_retry_at, needs_admin_review, created_at, updated_at
`

type UpdatePhoneVerificationStatusParams struct {
	ID              uuid.UUID     `json:"id"`
	Status          RequestStatus `json:"status"`
	FailureReason   pgtype.Text   `json:"failure_reason"`
	CampayPayoutRef pgtype.Text   `json:"campay_payout_ref"`
	UssdCode        pgtype.Text   `json:"ussd_code"`
}

func (q *Queries) UpdatePhoneVerificationStatus(ctx context.Context, arg UpdatePhoneVerificationStatusParams) (PhoneVerification, error) {
	row := q.db.QueryRow(ctx, updatePhoneVerificationStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.CampayPayoutRef,
		arg.UssdCode,
	)
	var i PhoneVerification
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.PhoneNumber,
		&i.AmountXaf,
		&i.CampayPayoutRef,
		&i.Status,
		&i.FailureReason,
		&i.UssdCode,
		&i.AttemptCount,
		&i.LastReconciledAt,
		&i.NextRetryAt,
		&i.NeedsAdminReview,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
