// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: refresh_tokens.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const cleanupExpiredRefreshTokens = `-- name: CleanupExpiredRefreshTokens :exec
DELETE FROM refresh_tokens WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredRefreshTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredRefreshTokens)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (token_hash, subject_id, subject_type, expires_at)
VALUES ($1, $2, $3, $4) RETURNING id, token_hash, subject_id, subject_type, expires_at, created_at
`

type CreateRefreshTokenParams struct {
	TokenHash   string    `json:"token_hash"`
	SubjectID   uuid.UUID `json:"subject_id"`
	SubjectType string    `json:"subject_type"`
	ExpiresAt   time.Time `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.TokenHash,
		arg.SubjectID,
		arg.SubjectType,
		arg.ExpiresAt,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SubjectID,
		&i.SubjectType,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, subject_id, subject_type, expires_at, created_at FROM refresh_tokens WHERE token_hash = $1 AND expires_at > NOW() LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.SubjectID,
		&i.SubjectType,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeAllRefreshTokensForSubject = `-- name: RevokeAllRefreshTokensForSubject :exec
DELETE FROM refresh_tokens WHERE subject_id = $1 AND subject_type = $2
`

type RevokeAllRefreshTokensForSubjectParams struct {
	SubjectID   uuid.UUID `json:"subject_id"`
	SubjectType string    `json:"subject_type"`
}

func (q *Queries) RevokeAllRefreshTokensForSubject(ctx context.Context, arg RevokeAllRefreshTokensForSubjectParams) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForSubject, arg.SubjectID, arg.SubjectType)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
DELETE FROM refresh_tokens WHERE token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}
