// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    company_id, email, email_verified, full_name,
    phone_number, phone_verified, status,
    pin_hash
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type CreateUserParams struct {
	CompanyID     uuid.UUID   `json:"company_id"`
	Email         string      `json:"email"`
	EmailVerified bool        `json:"email_verified"`
	FullName      pgtype.Text `json:"full_name"`
	PhoneNumber   pgtype.Text `json:"phone_number"`
	PhoneVerified bool        `json:"phone_verified"`
	Status        UserStatus  `json:"status"`
	PinHash       pgtype.Text `json:"pin_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.CompanyID,
		arg.Email,
		arg.EmailVerified,
		arg.FullName,
		arg.PhoneNumber,
		arg.PhoneVerified,
		arg.Status,
		arg.PinHash,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users WHERE email = $1 LIMIT 1
`

// Pre-auth resolution: user email is globally unique. Returns company_id.
func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users WHERE id = $1 LIMIT 1
`

// Self lookup: id comes from the authenticated claim; caller asserts company match.
func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByPhoneNumber = `-- name: GetUserByPhoneNumber :one
SELECT id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users WHERE phone_number = $1 LIMIT 1
`

func (q *Queries) GetUserByPhoneNumber(ctx context.Context, phoneNumber pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, getUserByPhoneNumber, phoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementFailedLoginAttempts = `-- name: IncrementFailedLoginAttempts :one
UPDATE users SET failed_login_attempts = failed_login_attempts + 1, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

func (q *Queries) IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, incrementFailedLoginAttempts, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByCompany = `-- name: ListUsersByCompany :many
SELECT id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at FROM users
WHERE company_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUsersByCompanyParams struct {
	CompanyID uuid.UUID `json:"company_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
}

func (q *Queries) ListUsersByCompany(ctx context.Context, arg ListUsersByCompanyParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByCompany, arg.CompanyID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.CompanyID,
			&i.Email,
			&i.EmailVerified,
			&i.FullName,
			&i.PhoneNumber,
			&i.PhoneVerified,
			&i.PinHash,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.Status,
			&i.IsTermsAccepted,
			&i.TermsAcceptedAt,
			&i.TermsVersion,
			&i.UserIpAtConsent,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockUser = `-- name: LockUser :one
UPDATE users SET status = 'locked', updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

func (q *Queries) LockUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, lockUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUserUntil = `-- name: LockUserUntil :one
UPDATE users SET locked_until = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type LockUserUntilParams struct {
	ID          uuid.UUID          `json:"id"`
	LockedUntil pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) LockUserUntil(ctx context.Context, arg LockUserUntilParams) (User, error) {
	row := q.db.QueryRow(ctx, lockUserUntil, arg.ID, arg.LockedUntil)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const resetLoginAttempts = `-- name: ResetLoginAttempts :one
UPDATE users SET failed_login_attempts = 0, locked_until = NULL, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

func (q *Queries) ResetLoginAttempts(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, resetLoginAttempts, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPhoneVerified = `-- name: SetPhoneVerified :one
UPDATE users SET phone_verified = true, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

func (q *Queries) SetPhoneVerified(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, setPhoneVerified, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unlockUser = `-- name: UnlockUser :one
UPDATE users SET status = 'active', failed_login_attempts = 0, locked_until = NULL, updated_at = NOW()
WHERE id = $1 AND company_id = $2 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UnlockUserParams struct {
	ID        uuid.UUID `json:"id"`
	CompanyID uuid.UUID `json:"company_id"`
}

// Admin action on a target user; scoped to the admin's company.
func (q *Queries) UnlockUser(ctx context.Context, arg UnlockUserParams) (User, error) {
	row := q.db.QueryRow(ctx, unlockUser, arg.ID, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePhoneNumber = `-- name: UpdatePhoneNumber :one
UPDATE users SET phone_number = $2, phone_verified = false, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UpdatePhoneNumberParams struct {
	ID          uuid.UUID   `json:"id"`
	PhoneNumber pgtype.Text `json:"phone_number"`
}

func (q *Queries) UpdatePhoneNumber(ctx context.Context, arg UpdatePhoneNumberParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePhoneNumber, arg.ID, arg.PhoneNumber)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTermsAcceptance = `-- name: UpdateTermsAcceptance :one
UPDATE users SET
    is_terms_accepted = $2,
    terms_accepted_at = $3,
    terms_version = $4,
    user_ip_at_consent = $5,
    updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UpdateTermsAcceptanceParams struct {
	ID              uuid.UUID          `json:"id"`
	IsTermsAccepted bool               `json:"is_terms_accepted"`
	TermsAcceptedAt pgtype.Timestamptz `json:"terms_accepted_at"`
	TermsVersion    pgtype.Text        `json:"terms_version"`
	UserIpAtConsent *netip.Addr        `json:"user_ip_at_consent"`
}

func (q *Queries) UpdateTermsAcceptance(ctx context.Context, arg UpdateTermsAcceptanceParams) (User, error) {
	row := q.db.QueryRow(ctx, updateTermsAcceptance,
		arg.ID,
		arg.IsTermsAccepted,
		arg.TermsAcceptedAt,
		arg.TermsVersion,
		arg.UserIpAtConsent,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPinHash = `-- name: UpdateUserPinHash :one
UPDATE users SET pin_hash = $2, updated_at = NOW()
WHERE id = $1 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UpdateUserPinHashParams struct {
	ID      uuid.UUID   `json:"id"`
	PinHash pgtype.Text `json:"pin_hash"`
}

func (q *Queries) UpdateUserPinHash(ctx context.Context, arg UpdateUserPinHashParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserPinHash, arg.ID, arg.PinHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE users SET status = $2, updated_at = NOW()
WHERE id = $1 AND company_id = $3 RETURNING id, company_id, email, email_verified, full_name, phone_number, phone_verified, pin_hash, failed_login_attempts, locked_until, status, is_terms_accepted, terms_accepted_at, terms_version, user_ip_at_consent, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID        uuid.UUID  `json:"id"`
	Status    UserStatus `json:"status"`
	CompanyID uuid.UUID  `json:"company_id"`
}

// Admin action on a target user; scoped to the admin's company.
func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.Status, arg.CompanyID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.Email,
		&i.EmailVerified,
		&i.FullName,
		&i.PhoneNumber,
		&i.PhoneVerified,
		&i.PinHash,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.Status,
		&i.IsTermsAccepted,
		&i.TermsAcceptedAt,
		&i.TermsVersion,
		&i.UserIpAtConsent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
